pipe line {
    agent any 
    stages{
        stage('checkout'){
            steps{
                  git branch :'main ',url:'https://github.com/awssalmanraju-code/sonarqube.git' 
            }
        }
    }
    }